### ISSUE TITLE
Uporaba DataSource in priprave PU [1 točka]

### ISSUE THREAD

**Issue by nyanSpruk** [bl4ko/PriceRunner#4]
- [x] V datoteki config.yaml modula api definirajte DataSource.
```yaml
kumuluzee:
  ...
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://localhost:5432/primerjalnikcen
      username: postgres
      password: postgres
```

- [x] V modulu entitete dodajte datoteko resources/META-INF/persistence.xml v kateri definirajte persistence-unit. 
- [x] Uporabite DataSource iz config.yaml ter določite ime in tip transakcije JTA.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence" version="2.1">
    <persistence-unit name="primerjalnik-cen-jpa" transaction-type="JTA">
        <jta-data-source>jdbc/PrimerjalnikCenDS</jta-data-source>

        <class><!-- vaše entitete --></class>
        <class><!-- vaše entitete --></class>

        <properties>
            <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
            <property name="javax.persistence.schema-generation.create-source" value="metadata"/>
            <property name="javax.persistence.sql-load-script-source" value="sql-scripts/init-db.sql"/>
            <property name="javax.persistence.schema-generation.drop-source" value="metadata"/>
        </properties>
    </persistence-unit>
</persistence>
```
Nalogi je priložen preprost primer skripte SQL za inicializacijo baze, ki jo predelajte, da bo ustrezala vašemu podatkovnemu modelu.
[Link to SQL file - init-db.sql](https://ucilnica.fri.uni-lj.si/pluginfile.php/8223/mod_assign/introattachment/0/init-db.sql?forcedownload=1)
